fixed variables fixed forgotten commandline switch for remote file

diff --git a/update_geoip b/update_geoip
--- a/update_geoip
+++ b/update_geoip
@@ -43,22 +43,22 @@ bold=`tput bold`
 normal=`tput sgr0`
 
 # catch the commandline arguments - if some given
-usage=`printf "Usage: %s [-p /path/to/destination/] [-i download URL]" "$filename"`
-while getopts "p:h" opt; do
-  case $opt in
-    p)  if [ -n $OPTARG ]; then
-    		geoIPPath=$OPTARG
+usage=`printf "Usage: ${filename} [-p /path/to/destination/] [-i download URL]"`
+while getopts "p:i:h" opt; do
+  case ${opt} in
+    p)  if [ -n ${OPTARG} ]; then
+    		geoIPPath=${OPTARG}
         fi
         ;;
-    i)  if [ -n $OPTARG ]; then
-    		IPAddress=$OPTARG
+    i)  if [ -n ${OPTARG} ]; then
+    		IPAddress=${OPTARG}
         fi
         ;;
-    h)  echo $usage
+    h)  echo ${usage}
         exit 0
         ;;
 
-    \?) echo "Invalid option: -$OPTARG" >&2
+    \?) echo "Invalid option: -${OPTARG}" >&2
         exit 1
         ;;
   esac
@@ -66,7 +66,7 @@ done
 
 # check the if the file exists
 echo -ne 'Checking if the remote File is available\r'
-httpResponse=$($curl --write-out %{http_code} --silent --output /dev/null $IPAddress)
+httpResponse=$(${curl} --write-out %{http_code} --silent --output /dev/null ${IPAddress})
 echo -ne 'Checking if the remote File is available.\r'
 sleep 1
 echo -ne 'Checking if the remote File is available..\r'
@@ -75,18 +75,18 @@ echo -ne 'Checking if the remote File is available...\r'
 sleep 1
 echo -ne '\n'
 
-if [ $httpResponse -eq 200 ]
+if [ ${httpResponse} -eq 200 ]
 	then
 		# yup it is online
 		echo "We're in luck they still provide the file"
 		sleep 1
 		echo 'Let me take a look if we have an existing GeoIP.dat'
 		sleep 1
-		if [ -e $geoIPPath/GeoIP.dat ] 
+		if [ -e ${geoIPPath}/GeoIP.dat ]
 			then
 				update=1
 				echo "Got one - I'll do a backup before proceed further"
-				mv $geoIPPath/GeoIP.dat $geoIPPath/GeoIP.dat_backup
+				mv ${geoIPPath}/GeoIP.dat ${geoIPPath}/GeoIP.dat_backup
 				sleep 1
 				echo 'Done!'
 			else
@@ -94,9 +94,9 @@ if [ $httpResponse -eq 200 ]
 		fi
 		echo 'receiving and extract the new file'
 		# thats the tricky part because I stream the download directly to zcat
-		# so we do not need to remove a downloaded file.
+		# so we do not need to remove a downloaded file later on.
 		# --> this will work in bash only <--
-		$zcat < <($wget -q -O -  $IPAddress) > $geoIPPath/GeoIP.dat
+		${zcat} < <(${wget} -q -O -  ${IPAddress}) > ${geoIPPath}/GeoIP.dat
 		echo -ne '#####                     (33%)\r'
 		sleep 1
 		echo -ne '#############             (66%)\r'
@@ -104,18 +104,16 @@ if [ $httpResponse -eq 200 ]
 		echo -ne '#######################   (100%)\r'
 		echo -ne '\n'
 		sleep 1
-		echo 'Download complete!'
-		sleep 1
-		if [ -z "$update" ];
+		if [ -z "${update}" ];
 			then
 				echo 'Download complete!'
 			else
 				echo 'Cleaning up'
-				rm -rf $geoIPPath/GeoIP.dat_backup
+				rm -rf ${geoIPPath}/GeoIP.dat_backup
 				sleep 1
 				echo 'Update complete'
 		fi
 	else
-		printf "\nNope, download failed\nThe requested file (${bold}%s${normal}) does not exist.\n" "$IPAddress"
+		printf "\nNope, download failed\nThe requested file (${bold}${IPAddress}${normal}) does not exist.\n"
 fi
 # EOF
